// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Selin and Heartline contributors

package com.heartline.phone

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.rounded.Accessibility
import androidx.compose.material.icons.rounded.Favorite
import androidx.compose.material.icons.rounded.MonitorHeart
import androidx.compose.material.icons.rounded.SelfImprovement
import androidx.compose.material.icons.rounded.Speed
import androidx.compose.material.icons.rounded.Thermostat
import androidx.compose.material.icons.rounded.WaterDrop
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathNode
import androidx.compose.ui.graphics.vector.VectorGroup
import androidx.compose.ui.graphics.vector.VectorPath
import org.junit.Assume.assumeTrue
import org.junit.Test
import java.io.File

/**
 * Writes the metric icons the app draws with Compose as Android vector drawables, for places
 * that can't use Compose: home-screen widgets (Glance) and watch tiles/complications.
 * Run with HEARTLINE_EXPORT_ICONS=1 ./gradlew :phone:testDebugUnitTest --tests '*IconExport*'.
 */
class IconExport {
    private val icons = mapOf(
        "ic_metric_heart" to Icons.Rounded.Favorite,
        "ic_metric_ecg" to Icons.Rounded.MonitorHeart,
        "ic_metric_bp" to Icons.Rounded.Speed,
        "ic_metric_spo2" to Icons.Rounded.WaterDrop,
        "ic_metric_temp" to Icons.Rounded.Thermostat,
        "ic_metric_body" to Icons.Rounded.Accessibility,
        "ic_metric_stress" to Icons.Rounded.SelfImprovement,
    )

    @Test
    fun export() {
        assumeTrue(System.getenv("HEARTLINE_EXPORT_ICONS") != null)
        val root = generateSequence(File("").absoluteFile) { it.parentFile }.first { File(it, "settings.gradle.kts").exists() }
        for (module in listOf("phone", "wear")) {
            val dir = File(root, "$module/src/main/res/drawable").apply { mkdirs() }
            icons.forEach { (name, icon) -> File(dir, "$name.xml").writeText(xml(icon)) }
        }
    }

    private fun xml(icon: ImageVector): String {
        val paths = buildList { collect(icon.root, this) }
        return buildString {
            appendLine("""<?xml version="1.0" encoding="utf-8"?>""")
            appendLine("<!-- Generated by IconExport from Material Icons (Rounded), Apache 2.0. Tinted where used. -->")
            appendLine("""<vector xmlns:android="http://schemas.android.com/apk/res/android"""")
            appendLine("""    android:width="24dp"""")
            appendLine("""    android:height="24dp"""")
            appendLine("""    android:viewportWidth="${icon.viewportWidth.clean()}"""")
            appendLine("""    android:viewportHeight="${icon.viewportHeight.clean()}">""")
            paths.forEach { d ->
                appendLine("    <path")
                appendLine("""        android:fillColor="#FFFFFFFF"""")
                appendLine("""        android:pathData="$d" />""")
            }
            appendLine("</vector>")
        }
    }

    private fun collect(group: VectorGroup, out: MutableList<String>) {
        group.forEach { node ->
            when (node) {
                is VectorGroup -> collect(node, out)
                is VectorPath -> out += node.pathData.joinToString(" ") { it.svg() }
            }
        }
    }

    private fun Float.clean() = if (this % 1f == 0f) toInt().toString() else toString()

    private fun PathNode.svg(): String = when (this) {
        is PathNode.MoveTo -> "M${x.clean()},${y.clean()}"
        is PathNode.RelativeMoveTo -> "m${dx.clean()},${dy.clean()}"
        is PathNode.LineTo -> "L${x.clean()},${y.clean()}"
        is PathNode.RelativeLineTo -> "l${dx.clean()},${dy.clean()}"
        is PathNode.HorizontalTo -> "H${x.clean()}"
        is PathNode.RelativeHorizontalTo -> "h${dx.clean()}"
        is PathNode.VerticalTo -> "V${y.clean()}"
        is PathNode.RelativeVerticalTo -> "v${dy.clean()}"
        is PathNode.CurveTo -> "C${x1.clean()},${y1.clean()} ${x2.clean()},${y2.clean()} ${x3.clean()},${y3.clean()}"
        is PathNode.RelativeCurveTo -> "c${dx1.clean()},${dy1.clean()} ${dx2.clean()},${dy2.clean()} ${dx3.clean()},${dy3.clean()}"
        is PathNode.ReflectiveCurveTo -> "S${x1.clean()},${y1.clean()} ${x2.clean()},${y2.clean()}"
        is PathNode.RelativeReflectiveCurveTo -> "s${dx1.clean()},${dy1.clean()} ${dx2.clean()},${dy2.clean()}"
        is PathNode.QuadTo -> "Q${x1.clean()},${y1.clean()} ${x2.clean()},${y2.clean()}"
        is PathNode.RelativeQuadTo -> "q${dx1.clean()},${dy1.clean()} ${dx2.clean()},${dy2.clean()}"
        is PathNode.ReflectiveQuadTo -> "T${x.clean()},${y.clean()}"
        is PathNode.RelativeReflectiveQuadTo -> "t${dx.clean()},${dy.clean()}"
        is PathNode.ArcTo ->
            "A${horizontalEllipseRadius.clean()},${verticalEllipseRadius.clean()} ${theta.clean()} ${if (isMoreThanHalf) 1 else 0},${if (isPositiveArc) 1 else 0} ${arcStartX.clean()},${arcStartY.clean()}"
        is PathNode.RelativeArcTo ->
            "a${horizontalEllipseRadius.clean()},${verticalEllipseRadius.clean()} ${theta.clean()} ${if (isMoreThanHalf) 1 else 0},${if (isPositiveArc) 1 else 0} ${arcStartDx.clean()},${arcStartDy.clean()}"
        PathNode.Close -> "Z"
    }
}
