name: Feature request
description: Suggest an idea or improvement
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Your idea
      description: How should it work on the watch and/or the phone?
    validations:
      required: true
  - type: checkboxes
    id: contribute
    attributes:
      label: Contribution
      options:
        - label: I'd like to implement this myself and send a pull request
